# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios2019' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

   pod 'SwiftySound'
   pod 'QRCodeReader.swift', '~> 10.0.0'
   pod 'Alamofire', '= 4.4'
   pod 'SwiftyJSON', '~> 4.2.0'
  # Pods for ios2019

  target 'ios2019Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ios2019UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
